name: Build proceeding PDF
on:
  push:
    branches:
      - master

env:
 PUB_NAME: ${{ github.event.repository.name }}
jobs:
  buildPDF:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'Initial commit')"
    container:
      image: agahkarakuzu/bhproceedings@sha256:bfc1b7f3b714b12e04a6a6ef1f440e9f19997ac1bfecc2187f2476cf47c22ab3

    steps:
     - name: Checkout repository
       uses: actions/checkout@v2
     - name: Compile PDF
       run: |
        mkdir -p data
        [ -e data/report.json ] && rm data/report.json
        [ -e data/ghdetails.json ] && rm data/ghdetails.json
        m2j report.md >> data/report.json
        cat <<EOF > data/ghdetails.json
        {"pub_name" : "${{env.PUB_NAME}}","repo":"$GITHUB_REPOSITORY"}
        EOF
        pandoc -s -N --template ./latex/brainhack-report-template.tex report.md -o ./latex/brainhack-${{env.PUB_NAME}}.tex
        pandoc -s -N --template ./latex/brainhack-html-template.tex report.md -o ./latex/brainhack-${{env.PUB_NAME}}-html.tex
        cd latex
        pdflatex brainhack-${{env.PUB_NAME}}.tex
        bibtex brainhack-${{env.PUB_NAME}}
        pdflatex brainhack-${{env.PUB_NAME}}.tex
        pdflatex brainhack-${{env.PUB_NAME}}.tex
        pandoc brainhack-${{env.PUB_NAME}}-html.tex -f latex -t html -s -o report.html --bibliography ../report.bib
        cp report.html ../layouts/partials/report.html
        mkdir -p ../static/pdf
        cp brainhack-${{env.PUB_NAME}}.pdf ../static/pdf/brainhack-${{env.PUB_NAME}}.pdf
     - uses: actions/upload-artifact@v2
       with:
         name: PDF Report ${{env.PUB_NAME}}
         path: static/pdf/brainhack-${{env.PUB_NAME}}.pdf
     - uses: actions/upload-artifact@v2
       with:
         name: HTML Report ${{env.PUB_NAME}}
         path: layouts/partials/report.html
     - uses: actions/upload-artifact@v2
       with:
         name: JSON Report ${{env.PUB_NAME}}
         path: data/report.json
     - uses: actions/upload-artifact@v2
       with:
         name: JSON GitHub ${{env.PUB_NAME}}
         path: data/ghdetails.json
  buildHugo:
   runs-on: ubuntu-latest
   if: "!contains(github.event.head_commit.message, 'Initial commit')"
   needs: buildPDF
   steps:  
     - name: Checkout repository
       uses: actions/checkout@v2
       with:
        submodules: true
        fetch-depth: 0
     - uses: actions/download-artifact@master
       with:
         name: PDF Report ${{env.PUB_NAME}}
         path: static/pdf
     - uses: actions/download-artifact@master
       with:
         name: HTML Report ${{env.PUB_NAME}}
         path: layouts/partials
     - uses: actions/download-artifact@master
       with:
         name: JSON Report ${{env.PUB_NAME}}
         path: data
     - uses: actions/download-artifact@master
       with:
         name: JSON GitHub ${{env.PUB_NAME}}
         path: data
     - name: Commit files
       run: |
        rsync -r figures/ static
        git config --local user.email "noreply@bhproceedings.com"
        git config --local user.name "BHBOT"
        git add static/pdf/brainhack-${{env.PUB_NAME}}.pdf
        git commit -m "[ADD] 🤖 Compiled PDF" -a
        ls ./static/pdf
     - name: Push changes
       uses: ad-m/github-push-action@master
       with:
        github_token: ${{ secrets.PAT_BOT }}   
     - name: Setup Hugo
       uses: peaceiris/actions-hugo@v2
       with:
         hugo-version: '0.71.1'
     - name: Build
       run: hugo --minify
       env:
          HUGO_PARAMS_github: ${{github.workspace}}
     - name: Deploy
       uses: peaceiris/actions-gh-pages@v3
       with:
         github_token: ${{ secrets.PAT_BOT }}
         publish_dir: ./public